export const Palette = {
  white: '#FFFFFF',
  softWhite: '#F6FAF7',
  forest: '#166534',
  green: '#16A34A',
  paleGreen: '#DCFCE7',
  nearBlack: '#101813',
  muted: '#526057',
  border: '#DCE5DE',
  disabled: '#E8ECE9',
  amber: '#B45309',
  red: '#B91C1C',
  blue: '#1D4ED8',
} as const;

export default {
  light: {
    text: Palette.nearBlack,
    textSecondary: Palette.muted,
    background: Palette.white,
    surface: Palette.softWhite,
    surfaceElevated: Palette.white,
    primary: Palette.forest,
    primaryInteractive: Palette.green,
    primarySoft: Palette.paleGreen,
    border: Palette.border,
    tint: Palette.forest,
    tabIconDefault: Palette.muted,
    tabIconSelected: Palette.forest,
    statusBar: 'dark' as const,
  },
  dark: {
    text: Palette.white,
    textSecondary: '#B7C4BA',
    background: '#0B110D',
    surface: '#111A14',
    surfaceElevated: '#17211A',
    primary: '#4ADE80',
    primaryInteractive: '#22C55E',
    primarySoft: '#173D25',
    border: '#2B3A2F',
    tint: '#4ADE80',
    tabIconDefault: '#8FA096',
    tabIconSelected: '#4ADE80',
    statusBar: 'light' as const,
  },
};
