export type CropCategory = 'all' | 'vegetables' | 'leafy_greens' | 'fruits' | 'root_crops' | 'grains' | 'spices';

export interface CategoryInfo {
  id: CropCategory;
  label: string;
  tagalogLabel: string;
}

export const CROP_CATEGORIES: CategoryInfo[] = [
  { id: 'all', label: 'All', tagalogLabel: 'Lahat' },
  { id: 'vegetables', label: 'Vegetables', tagalogLabel: 'Gulay' },
  { id: 'leafy_greens', label: 'Leafy Greens', tagalogLabel: 'Madahon' },
  { id: 'fruits', label: 'Fruits', tagalogLabel: 'Prutas' },
  { id: 'root_crops', label: 'Root Crops', tagalogLabel: 'Lamang-Lupa' },
  { id: 'grains', label: 'Grains', tagalogLabel: 'Butil' },
  { id: 'spices', label: 'Spices', tagalogLabel: 'Pampalasa' },
];

export interface AlmanacCrop {
  id: string;
  name: string;
  localName: string;
  scientificName: string;
  category: 'vegetables' | 'leafy_greens' | 'fruits' | 'root_crops' | 'grains' | 'spices';
  image: any | null;
  summary: string;
  plantingSeason: string;
  daysToHarvest: string;
  soilAndWater: string;
  sunlight: string;
  growingTips: string[];
}

// Dedicated image registry for all 35 Philippine crops
const IMAGES = {
  // Fruits (8)
  mangga: require('@/assets/Almanac/Fruits/mangga.png'),
  saging: require('@/assets/Almanac/Fruits/saging.png'),
  calamansi: require('@/assets/Almanac/Fruits/calamansi.png'),
  papaya: require('@/assets/Almanac/Fruits/papaya.png'),
  pinya: require('@/assets/Almanac/Fruits/pinya.png'),
  pakwan: require('@/assets/Almanac/Fruits/pakwan.png'),
  bayabas: require('@/assets/Almanac/Fruits/bayabas.png'),
  guyabano: require('@/assets/Almanac/Fruits/guyabano.png'),

  // Vegetables (7)
  ampalaya: require('@/assets/Almanac/Vegetables/ampalaya.png'),
  talong: require('@/assets/Almanac/Vegetables/talong.png'),
  kalabasa: require('@/assets/Almanac/Vegetables/kalabasa.png'),
  kamatis: require('@/assets/Almanac/Vegetables/kamatis.png'),
  sitaw: require('@/assets/Almanac/Vegetables/sitaw.png'),
  okra: require('@/assets/Almanac/Vegetables/okra.png'),
  patola: require('@/assets/Almanac/Vegetables/patola.png'),
  upo: require('@/assets/Almanac/Vegetables/upo.png'),
  sigarilyas: require('@/assets/Almanac/Vegetables/sigarilyas.png'),

  // Leafy Greens (6)
  pechay: require('@/assets/Almanac/LeafyGreens/pechay.png'),
  kangkong: require('@/assets/Almanac/LeafyGreens/kangkong.png'),
  malunggay: require('@/assets/Almanac/LeafyGreens/malunggay.png'),
  mustasa: require('@/assets/Almanac/LeafyGreens/mustasa.png'),
  saluyot: require('@/assets/Almanac/LeafyGreens/saluyot.png'),
  kulitis: require('@/assets/Almanac/LeafyGreens/kulitis.png'),

  // Root Crops (4)
  kamote: require('@/assets/Almanac/RootCrops/kamote.png'),
  kamoteng_kahoy: require('@/assets/Almanac/RootCrops/kamoteng_kahoy.png'),
  gabi: require('@/assets/Almanac/RootCrops/gabi.png'),
  ube: require('@/assets/Almanac/RootCrops/ube.png'),

  // Grains (2)
  palay: require('@/assets/Almanac/Grains/palay.png'),
  mais: require('@/assets/Almanac/Grains/mais.png'),

  // Spices (6)
  siling_labuyo: require('@/assets/Almanac/Spices/siling_labuyo.png'),
  siling_haba: require('@/assets/Almanac/Spices/siling_haba.png'),
  bawang: require('@/assets/Almanac/Spices/bawang.png'),
  sibuyas: require('@/assets/Almanac/Spices/sibuyas.png'),
  luya: require('@/assets/Almanac/Spices/luya.png'),
  tanglad: require('@/assets/Almanac/Spices/tanglad.png'),
};

export const BOTANICAL_PLACEHOLDER = require('@/assets/Almanac/botanical-placeholder.png');

export const ALMANAC_CROPS: AlmanacCrop[] = [
  // ==========================================
  // FRUITS (Prutas)
  // ==========================================
  {
    id: 'mangga',
    name: 'Carabao Mango',
    localName: 'Mangga',
    scientificName: 'Mangifera indica',
    category: 'fruits',
    image: IMAGES.mangga,
    summary: 'The national fruit of the Philippines, world-renowned for its silky smooth, golden-yellow skin and unmatched sweetness. Thrives in well-drained lowland areas.',
    plantingSeason: 'October to February (end of rainy season)',
    daysToHarvest: '3–5 years from grafted sapling; 110–120 days from full bloom',
    soilAndWater: 'Deep, fertile, well-drained loam. Deep watering during vegetative growth; dry spell needed for floral induction.',
    sunlight: 'Full direct sunlight (at least 8 hours daily)',
    growingTips: [
      'Flower induction using potassium nitrate is commonly timed with dry weather.',
      'Bag young fruits at 55–60 days after blooming to protect against fruit flies.',
      'Prune dead or crisscrossing inner branches to promote aeration and canopy sunlight.',
    ],
  },
  {
    id: 'saging',
    name: 'Banana',
    localName: 'Saging',
    scientificName: 'Musa acuminata / balbisiana',
    category: 'fruits',
    image: IMAGES.saging,
    summary: 'Essential tropical staple grown nationwide in varieties like Lakatan, Latundan, and Saba. Fast-producing and thrives in warm, humid Philippine lowlands.',
    plantingSeason: 'Year-round; best at the onset of the rainy season (May–June)',
    daysToHarvest: '9–12 months from planting suckers',
    soilAndWater: 'Rich, moisture-retentive organic soil with good drainage. Requires regular weekly irrigation and heavy mulching.',
    sunlight: 'Full sunlight to partial light with wind protection',
    growingTips: [
      'De-sucker regularly, maintaining 1 mother plant, 1 follower, and 1 sucker.',
      'Propping with bamboo poles prevents pseudostems from toppling during heavy bunching.',
      'Remove male blossom bud (puso) once the last banana hand emerges to divert energy to fruit.',
    ],
  },
  {
    id: 'calamansi',
    name: 'Calamansi',
    localName: 'Kalamansi',
    scientificName: 'Citrus microcarpa',
    category: 'fruits',
    image: IMAGES.calamansi,
    summary: 'A cornerstone of Philippine agriculture and everyday culinary life, Calamansi is the premier native citrus cultivated widely in Oriental Mindoro, Quezon, and Davao. Prized for its tart, aromatic juice used in sawsawan dipping sauces, marinades like bistek, and vitamin-rich juices.',
    plantingSeason: 'May to October (onset of rainy season); year-round with irrigation',
    daysToHarvest: '2–3 years from grafted saplings; 120–150 days from bloom to harvest',
    soilAndWater: 'Well-drained sandy loam or clay loam rich in organic matter (pH 5.5–6.5). Highly sensitive to waterlogging; requires regular watering during blooming and fruit sizing.',
    sunlight: 'Full direct sunlight (at least 6–8 hours daily)',
    growingTips: [
      'Induce off-season flowering by withholding irrigation for 2–3 weeks during the dry season, followed by deep watering and foliar potassium nitrate.',
      'Prune water sprouts (suckers) and diseased twigs after peak harvest to improve ventilation and curb citrus rind borer.',
      'Scout for the Asian citrus psyllid (Diaphorina citri) and spray neem oil or horticultural soap against leaf miners and scales.',
      'Apply balanced 14-14-14 NPK during active flushes and supplement with muriate of potash (0-0-60) during fruit enlargement.',
    ],
  },
  {
    id: 'papaya',
    name: 'Papaya',
    localName: 'Papaya',
    scientificName: 'Carica papaya',
    category: 'fruits',
    image: IMAGES.papaya,
    summary: 'A fast-maturing, high-value tropical crop cultivated across Cavite, Batangas, Bukidnon, and Davao. Major cultivars include the sweet red-fleshed Red Lady F1 hybrid, Sinta, and Solo types. It plays an essential dual role in Filipino cuisine, harvested green for tinola broth and pickled atsara, or fully ripe as a table fruit.',
    plantingSeason: 'May to June (early wet season) or October to December with irrigation',
    daysToHarvest: '7–9 months from transplanting (green fruit at 6–7 months; ripe at 8–10 months)',
    soilAndWater: 'Deep, porous, well-draining sandy loam or volcanic loam (pH 6.0–6.5). Intolerant of standing water and root rot; requires 30–50 cm raised mounds.',
    sunlight: 'Full direct sunlight (6–8 hours minimum daily)',
    growingTips: [
      'Plant 3 seedlings per hill spaced 25 cm apart; once flowering begins at 3–4 months, rogue out all female and male plants, leaving only the elongated hermaphrodite plant.',
      'Construct 30–50 cm elevated planting mounds with deep furrows to prevent collar rot during heavy monsoon rains.',
      'Manage Papaya Ringspot Virus (PRSV) by selecting tolerant varieties like Sinta and spraying neem oil to suppress aphid vectors.',
      'Apply balanced NPK monthly and spray foliar borax to prevent bumpy fruit physiological disorder.',
    ],
  },
  {
    id: 'pinya',
    name: 'Pineapple',
    localName: 'Pinya',
    scientificName: 'Ananas comosus',
    category: 'fruits',
    image: IMAGES.pinya,
    summary: 'One of the top agricultural dollar-earners of the Philippines, pineapple thrives in the volcanic soils of Bukidnon, South Cotabato, and Camarines Norte. Renowned commercial varieties include the intensely sweet and crisp Queen (Formosa) and Smooth Cayenne (MD2). Beyond canning, it flavors pininyahang manok and yields piña fiber for the barong Tagalog.',
    plantingSeason: 'March to August (optimal planting in May–June coinciding with early rains)',
    daysToHarvest: '14–18 months from slips or suckers (18–24 months from crowns)',
    soilAndWater: 'Well-aerated, acidic sandy loam or volcanic loam (pH 4.5–5.5). Exceptional drought tolerance, but requires supplemental moisture during early growth and fruit sizing.',
    sunlight: 'Full, unshaded direct sunlight (8+ hours daily)',
    growingTips: [
      'Trigger uniform off-season flowering at 8–10 months (30–35 functional leaves) by dosing ethephon or calcium carbide (kalburo) solution into the heart at twilight.',
      'Cover maturing fruits with dry rice straw or bent lower leaves during intense dry months to prevent sunburn and core breakdown.',
      'Cure selected 300–400g slips or suckers in the shade for 3–5 days after stripping lower leaves to prevent heart and basal butt rot.',
      'Supply high-potassium nutrition from month 4 through fruit maturation to boost fruit size and internal sweetness (Brix).',
    ],
  },
  {
    id: 'pakwan',
    name: 'Watermelon',
    localName: 'Pakwan',
    scientificName: 'Citrullus lanatus',
    category: 'fruits',
    image: IMAGES.pakwan,
    summary: 'A fast-growing, high-earning cash crop extensively cultivated in Central Luzon, Ilocos, and Panay as a dry-season rotation crop following rice harvest. Popular cultivars include Sugar Baby, Sweet Greta, and Red Jewel F1. Celebrated for its crisp, thirst-quenching sweet flesh, it serves as the quintessential summer refreshment.',
    plantingSeason: 'October to January (dry season post-rice harvest to target peak summer demand from February to May)',
    daysToHarvest: '65–85 days from seed sowing (75–85 days for hybrid varieties)',
    soilAndWater: 'Light, fertile sandy loam or alluvial riverbed soil (pH 6.0–6.8) with superior drainage. Requires steady watering from germination through fruit swelling, followed by a dry-down before harvest.',
    sunlight: 'Full direct sunlight (8–10 hours daily) across open fields',
    growingTips: [
      'Install silver-gray reflective plastic mulch over raised beds to control weeds, conserve moisture, deter thrips and aphids, and isolate fruits from ground rot.',
      'Prune secondary lateral vines and thin developing melons to 1–2 well-shaped fruits per vine between the 10th and 15th leaf nodes.',
      'Cut off or strictly taper irrigation 10–14 days before harvest to concentrate sugars (Brix), prevent cracking, and ensure crisp, sweet flesh.',
      'Place clean rice straw cushions under developing melons to prevent soil rot and yellow belly spots while monitoring for fruit flies.',
    ],
  },
  {
    id: 'bayabas',
    name: 'Guava',
    localName: 'Bayabas',
    scientificName: 'Psidium guajava',
    category: 'fruits',
    image: IMAGES.bayabas,
    summary: 'A hardy and culturally cherished fruit grown across Philippine backyards and commercial orchards in Guimaras, Laguna, and Cavite. It is savored fresh with rock salt, provides the authentic souring base for Sinigang sa Bayabas, and its astringent leaves are widely used in traditional antiseptic decoctions.',
    plantingSeason: 'May to August (rainy season) for establishing saplings; year-round under irrigation',
    daysToHarvest: '1–2 years from grafted or marcotted saplings (90–120 days from flowering to mature fruit)',
    soilAndWater: 'Adaptable to various soils from sandy loam to clay loam (pH 5.0–7.0). Tolerates temporary drought once established; regular watering during flowering and fruit sizing prevents fruit drop.',
    sunlight: 'Full direct sunlight (6–8 hours daily)',
    growingTips: [
      'Bag individual fruitlets with perforated plastic sleeves or paper bags at 2–3 cm diameter for 100% protection against Oriental fruit flies and guava scab.',
      'Prune branch terminal tips back to 2–4 nodes after every harvesting cycle to force new vegetative flushes which bear subsequent flower buds.',
      'Install methyl eugenol pheromone traps around the orchard perimeter and promptly bury fallen or infested fruits.',
      'Apply complete 14-14-14 fertilizer quarterly, supplementing with potassium sulfate (0-0-50) during fruit enlargement for flesh crispness and sweetness.',
    ],
  },
  {
    id: 'guyabano',
    name: 'Soursop',
    localName: 'Guyabano',
    scientificName: 'Annona muricata',
    category: 'fruits',
    image: IMAGES.guyabano,
    summary: 'A high-value fruit crop renowned in the Philippines for both its delightful dessert qualities and widespread reputation as a wellness superfood. Its fibrous, subacid, creamy white pulp is eaten fresh, transformed into juices, shakes, and ice candy, while its dried leaves are brewed into an herbal tea.',
    plantingSeason: 'May to July (onset of southwest monsoon); year-round with irrigation and wind protection',
    daysToHarvest: '3–4 years from grafted saplings (100–120 days from pollination to harvest)',
    soilAndWater: 'Deep, friable, well-draining sandy loam or volcanic loam (pH 5.5–6.5). Highly vulnerable to waterlogging; requires regular, moderate irrigation during dry spells to prevent flower abortion.',
    sunlight: 'Full direct sunlight (6–8 hours daily); requires sheltered topography or windbreaks due to brittle branches',
    growingTips: [
      'Conduct manual hand pollination in early morning (5:30 AM to 7:30 AM) using a soft brush to ensure complete fertilization and avoid lopsided fruits.',
      'Bag young fruits with fine mesh netting or breathable bags when they reach fist size to ward off guyabano fruit borers and mealybugs.',
      'Prune the central leader to keep the canopy low (below 3 meters) for convenient bagging and harvesting, and establish perimeter windbreaks.',
      'Spray copper fungicides during wet-season bloom and prune dead inner twigs to maintain air movement and control anthracnose.',
    ],
  },

  // ==========================================
  // VEGETABLES & PODS (Gulay at Sitaw)
  // ==========================================
  {
    id: 'ampalaya',
    name: 'Bitter Gourd / Bitter Melon',
    localName: 'Ampalaya',
    scientificName: 'Momordica charantia',
    category: 'vegetables',
    image: IMAGES.ampalaya,
    summary: 'Iconic Philippine gourd with distinct dark-green ridges and medicinal bitter compounds. A high-value culinary staple in pinakbet, sautéed dishes, and tea.',
    plantingSeason: 'October to February (dry season) or May to July (wet season)',
    daysToHarvest: '55–65 days after seeding',
    soilAndWater: 'Well-aerated sandy loam with compost. Consistent watering without waterlogging.',
    sunlight: 'Full sun; requires sturdy vertical trellis support',
    growingTips: [
      'Construct a sturdy overhead trellis (balag) to allow straight, unblemished gourds.',
      'Wrap young hanging fruits with newspaper or netting to prevent fruit fly stinging.',
      'Harvest fruits while firm and green before seeds turn red and flesh softens.',
    ],
  },
  {
    id: 'talong',
    name: 'Eggplant',
    localName: 'Talong',
    scientificName: 'Solanum melongena',
    category: 'vegetables',
    image: IMAGES.talong,
    summary: 'The top commercial vegetable produced in the Philippines. Elongated glossy purple fruit prized for tortang talong, pinakbet, and grilling.',
    plantingSeason: 'October to March (optimal dry season with irrigation)',
    daysToHarvest: '70–85 days from transplanting',
    soilAndWater: 'Deep, friable clay loam or sandy loam rich in organic matter. Water at the base 2–3 times a week.',
    sunlight: 'Full sun (minimum 6–8 hours direct sunlight)',
    growingTips: [
      'Transplant sturdy seedlings into raised beds with compost 3–4 weeks after germination.',
      'Scout regularly for shoot and fruit borers; remove and dispose of damaged tips.',
      'Harvest with a sharp pair of shears leaving 2–3 cm of the green calyx stem attached.',
    ],
  },
  {
    id: 'kalabasa',
    name: 'Calabaza Squash',
    localName: 'Kalabasa',
    scientificName: 'Cucurbita moschata',
    category: 'vegetables',
    image: IMAGES.kalabasa,
    summary: 'Vigorous sprawling vine yielding large ribbed gourds with mottled green-orange skin and dense, sweet golden flesh. Both fruits and yellow blossoms are edible.',
    plantingSeason: 'October to January for dry crop; May to June for wet season',
    daysToHarvest: '90–110 days after planting',
    soilAndWater: 'Fertile, well-draining loamy soil with neutral pH. Water deeply at the roots avoiding leaves.',
    sunlight: 'Full, unshaded sunlight with ample sprawling ground or trellis space',
    growingTips: [
      'Plant in mounds with rich compost to enhance root warmth and drainage.',
      'Hand-pollinate female flowers in the early morning for higher fruit set.',
      'Harvest when the stem turns corky and woody, and rind resists thumbnail puncture.',
    ],
  },
  {
    id: 'kamatis',
    name: 'Tomato',
    localName: 'Kamatis',
    scientificName: 'Solanum lycopersicum',
    category: 'vegetables',
    image: IMAGES.kamatis,
    summary: 'An essential aromatic foundation in Filipino cooking, kamatis is sautéed with garlic and onions in everyday guisado and lends vibrant acidity to classic soups like Sinigang and Pinangat, or paired fresh with salted egg and bagoong.',
    plantingSeason: 'October to February (optimal dry season); May to August (under rain shelters)',
    daysToHarvest: '60–75 days after transplanting (85–100 days from seeding)',
    soilAndWater: 'Deep, well-draining sandy loam or clay loam (pH 6.0–6.8) rich in compost. Water at root base 2–3 times weekly; avoid wetting foliage.',
    sunlight: 'Full sun (6–8 hours daily). Requires bamboo staking to keep fruit clusters off damp soil.',
    growingTips: [
      'Stake plants with bamboo poles 2–3 weeks after transplanting and tie stems loosely with twine to support fruit clusters.',
      'Scout weekly for tomato fruitworms and whiteflies; spray neem oil or Bacillus thuringiensis (Bt) during early pest emergence.',
      'Side-dress with balanced fertilizer (14-14-14) at early growth and supplement with potassium during fruiting to prevent blossom-end rot.',
      'Harvest early morning at the breaker stage (light pink or orange blush) to extend shelf life during transport.',
    ],
  },
  {
    id: 'sitaw',
    name: 'Yardlong Bean',
    localName: 'Sitaw',
    scientificName: 'Vigna unguiculata subsp. sesquipedalis',
    category: 'vegetables',
    image: IMAGES.sitaw,
    summary: 'One of the most popular pod legumes across the Philippines, sitaw is an irreplaceable staple in Sinigang, Pinakbet, Dinengdeng, and Adobong Sitaw. Produces slender, tender pods up to 60 cm in length and enriches soil with nitrogen.',
    plantingSeason: 'October to February (optimal dry season); May to June (wet season onset)',
    daysToHarvest: '45–55 days from direct seeding',
    soilAndWater: 'Loose, well-aerated sandy loam or loam with pH 5.5–6.8. Water moderately 2–3 times a week; plant on raised furrows.',
    sunlight: 'Full sun (6–8 hours daily). Requires a 1.8–2.0 meter bamboo A-frame trellis to support climbing vines and maintain straight pods.',
    growingTips: [
      'Direct-seed 2–3 seeds per hill spaced 30 cm apart along raised beds, thinning to the 2 healthiest seedlings per hill.',
      'Construct a bamboo A-frame trellis early (10–14 days after emergence) before vines begin trailing on the ground.',
      'Manage black bean aphids and pod borers using wood ash dusting, neem seed kernel extract, or insecticidal soap sprays.',
      'Harvest pods every 2–3 days early in the morning while seeds are immature and pods snap cleanly.',
    ],
  },
  {
    id: 'okra',
    name: "Lady's Finger",
    localName: 'Okra',
    scientificName: 'Abelmoschus esculentus',
    category: 'vegetables',
    image: IMAGES.okra,
    summary: 'A staple warm-season vegetable across the archipelago, okra is celebrated for its tender texture and natural thickening mucilage in Pinakbet, Sinigang, and boiled Ensaladang Okra dressed with bagoong and calamansi.',
    plantingSeason: 'Year-round in warm lowlands; optimal October to March and May to June',
    daysToHarvest: '50–65 days from direct seeding',
    soilAndWater: 'Well-drained sandy loam or clay loam with organic matter (pH 6.0–7.5). Deep watering once or twice weekly; highly drought-resilient once rooted.',
    sunlight: 'Full direct sun (6–8 hours daily). Self-supporting upright shrub that thrives in hot tropical weather.',
    growingTips: [
      'Soak seeds in room-temperature water for 12–24 hours before sowing to soften the hard seed coat and accelerate germination.',
      'Basal-apply organic compost before planting, side-dressing with complete fertilizer (14-14-14) at 20 and 45 days after emergence.',
      'Monitor leaf undersides for cotton aphids and flea beetles; apply fermented plant juice (FPJ) or chili-garlic spray.',
      'Harvest pods when 7–10 cm long while tips snap easily; use shears and wear long sleeves to prevent skin irritation.',
    ],
  },
  {
    id: 'patola',
    name: 'Sponge Gourd / Silk Gourd',
    localName: 'Patola',
    scientificName: 'Luffa acutangula',
    category: 'vegetables',
    image: IMAGES.patola,
    summary: 'A beloved comfort food ingredient in Filipino kitchens, patola is prized for its sweet, delicate sponge flesh in Miswa at Patola, Ginisang Patola, and Dinengdeng. The vigorous climbing vine produces elongated green gourds with prominent longitudinal ridges.',
    plantingSeason: 'October to February (dry season); May to July (rainy season on raised beds)',
    daysToHarvest: '55–70 days from direct seeding',
    soilAndWater: 'Humus-rich, well-aerated sandy loam with pH 6.0–6.8. Regular, consistent watering at soil level; moisture stress results in bitter gourds.',
    sunlight: 'Full sun (6–8 hours daily). Requires an overhead horizontal bamboo trellis (balag) at least 1.8–2.0 meters high.',
    growingTips: [
      'Build a sturdy horizontal bamboo trellis (balag) to allow fruits to hang vertically and develop straight, unblemished gourds.',
      'Bag young developing gourds with perforated paper wrappers or fruit-fly netting immediately after flower petal drop.',
      'Pinch the terminal shoot when the main vine reaches the top of the trellis to promote lateral branches where female flowers emerge.',
      'Harvest every 3–4 days while gourds are tender and ribs are soft to the touch; overgrown gourds turn fibrous.',
    ],
  },
  {
    id: 'upo',
    name: 'Bottle Gourd',
    localName: 'Upo',
    scientificName: 'Lagenaria siceraria',
    category: 'vegetables',
    image: IMAGES.upo,
    summary: 'An enduring favorite in Philippine home cooking, upo features prominently in comforting stews such as Ginisang Upo with ground pork or shrimp and regional vegetable broths. It bears nocturnal white flowers and large, pale green bottle-shaped fruits with succulent white flesh.',
    plantingSeason: 'October to January (optimal dry season); May to June (wet season onset on raised mounds)',
    daysToHarvest: '60–80 days from direct seeding',
    soilAndWater: 'Deep, fertile sandy loam or silty loam with pH 6.0–7.0. Water deeply at the root zone every 2–3 days during fruit sizing.',
    sunlight: 'Full direct sun (6–8 hours daily). Demands a heavy-duty bamboo overhead trellis (balag) reinforced to bear heavy hanging fruits.',
    growingTips: [
      'Construct a heavy-duty bamboo trellis frame reinforced with diagonal bracing to support heavy, water-dense hanging fruits.',
      'Perform hand-pollination of the white female flowers in the late afternoon or early evening when blossoms open to improve fruit set.',
      'Wrap young developing fruits with protective paper or cloth sleeves right after fruit set to guard against fruit fly oviposition.',
      'Harvest while the rind remains light green, smooth, and easily pierced with a fingernail; cut leaving 4–5 cm of stem attached.',
    ],
  },
  {
    id: 'sigarilyas',
    name: 'Winged Bean',
    localName: 'Sigarilyas',
    scientificName: 'Psophocarpus tetragonolobus',
    category: 'vegetables',
    image: IMAGES.sigarilyas,
    summary: 'Immortalized in the Filipino folk song Bahay Kubo, sigarilyas is a prized heritage crop renowned for its tender, crunchy winged pods featured in Gising-Gising, Pinakbet, and fresh salads. Nearly every part is edible, including its young shoots, blue flowers, green pods, and tubers.',
    plantingSeason: 'May to August (traditional varieties); October to December (modern day-neutral cultivars)',
    daysToHarvest: '70–90 days from direct seeding',
    soilAndWater: 'Well-drained loam or sandy clay loam with pH 5.5–6.5. Moderate watering 1–2 times weekly; drought-tolerant once established.',
    sunlight: 'Full sun (minimum 6 hours daily). Requires a strong 2-meter tall bamboo pole, A-frame, or vertical trellis.',
    growingTips: [
      'Scarify the hard seed coat by rubbing gently with sandpaper and soaking in warm water overnight to ensure rapid, even sprouting.',
      'Erect sturdy 2-meter bamboo stakes or an A-frame trellis within 2 weeks of germination to support heavy vegetative canopy growth.',
      'Avoid excess synthetic nitrogen fertilizers which cause excessive vine growth at the expense of floral initiation and pod production.',
      'Harvest young, tender pods every 2–3 days when they reach 10–15 cm long while wings are crisp and flexible.',
    ],
  },

  // ==========================================
  // LEAFY GREENS (Madahong Gulay)
  // ==========================================
  {
    id: 'pechay',
    name: 'Philippine Cabbage / Bok Choy',
    localName: 'Pechay',
    scientificName: 'Brassica rapa subsp. chinensis',
    category: 'leafy_greens',
    image: IMAGES.pechay,
    summary: 'An indispensable leafy vegetable in Filipino comfort stews like Nilagang Baka, Bulalo, and Pochero, as well as quick stir-fries. Rich in vitamins A, C, calcium, and dietary fiber, it forms an upright loose rosette of crisp white petioles and broad green leaves.',
    plantingSeason: 'Year-round; optimal growth from October to February (cool-dry season)',
    daysToHarvest: '25–35 days from transplanting (35–45 days from direct seeding)',
    soilAndWater: 'Fertile, well-draining sandy loam or clay loam rich in organic matter (pH 5.8–6.8). Requires consistent watering 1–2 times daily.',
    sunlight: 'Full sunlight to partial shade (4–6 hours daily; light noon shading prevents bolting in hot summer months)',
    growingTips: [
      'Practice succession planting by sowing small batches every 10–14 days for a continuous household harvest.',
      'Harvest using the cut-and-come-again method by taking outer leaves first, allowing inner leaves to develop.',
      'Control flea beetles and caterpillars organically by spraying a botanical concoction of chili, garlic, and mild dish soap.',
      'Incorporate carbonized rice hull (CRH) and vermicompost into raised beds to maximize soil aeration and drainage.',
    ],
  },
  {
    id: 'kangkong',
    name: 'Water Spinach / Swamp Cabbage',
    localName: 'Kangkong',
    scientificName: 'Ipomoea aquatica',
    category: 'leafy_greens',
    image: IMAGES.kangkong,
    summary: 'A quintessential Filipino green featured prominently in sour broths like Sinigang, savory Adobong Kangkong, and crispy deep-fried appetizers. Packed with iron, beta-carotene, vitamin C, and dietary fiber, it is celebrated for combating anemia and supporting eye health.',
    plantingSeason: 'Year-round; grows most aggressively during the monsoon season (May to November)',
    daysToHarvest: '20–30 days from seeding or stem cuttings',
    soilAndWater: 'Adaptable to damp garden loam, muddy clay, or standing shallow water high in organic matter. Demands abundant moisture.',
    sunlight: 'Full direct sunlight (6–8 hours daily) for thick stems and lush foliage',
    growingTips: [
      'Regrow effortlessly from kitchen market cuttings by placing 15–20 cm mature stems in water or wet mud to root in 3–5 days.',
      'Harvest by cutting shoots 5 cm above soil level, stimulating multiple branching flushes every 10–14 days.',
      'Feed weekly with fermented plant juice (FPJ) or diluted vermitea to sustain high nitrogen levels for rapid leaf growth.',
      'Construct lined sub-irrigated planting troughs or raised mud beds to retain standing water during the dry summer season.',
    ],
  },
  {
    id: 'malunggay',
    name: 'Moringa / Drumstick Tree',
    localName: 'Malunggay',
    scientificName: 'Moringa oleifera',
    category: 'leafy_greens',
    image: IMAGES.malunggay,
    summary: 'Celebrated across the Philippines as the miracle tree and natural galactagogue, its tender leaflets are mandatory in Tinolang Manok, Suam na Mais, and Ginisang Monggo. It is a world-class superfood dense with complete plant protein, calcium, iron, potassium, and vitamins.',
    plantingSeason: 'Year-round; best planted at the onset of the rainy season (May to June)',
    daysToHarvest: '60–90 days from hardwood cuttings; continuous harvest once established',
    soilAndWater: 'Well-drained sandy or sandy loam soil (pH 6.3–7.0). Highly drought-tolerant once rooted; sensitive to standing water and poor drainage.',
    sunlight: 'Full, direct tropical sunlight (6–8+ hours daily)',
    growingTips: [
      'Propagate using mature hardwood cuttings (1 meter long, 3–5 cm diameter) planted 30 cm deep for rapid establishment.',
      'Prune the central leader at 1.5–2 meters to foster a low, bushy hedge canopy that allows comfortable hand harvesting.',
      'Strip only side leaflets during harvest, leaving the terminal growing tips intact to encourage new flush development.',
      'Top-dress the root zone twice a year with composted livestock manure and dried leaf mulch to preserve soil microbial life.',
    ],
  },
  {
    id: 'mustasa',
    name: 'Mustard Greens',
    localName: 'Mustasa',
    scientificName: 'Brassica juncea',
    category: 'leafy_greens',
    image: IMAGES.mustasa,
    summary: 'Prized in Philippine culinary traditions for its zesty, peppery pungency, it is the key ingredient in fermented Burong Mustasa and sour fish Sinigang sa Miso. It provides excellent concentrations of vitamin K, vitamin A, folate, and glucosinolates.',
    plantingSeason: 'Year-round; best performance and milder flavor during the cooler months (October to February)',
    daysToHarvest: '25–40 days after direct seeding (20–30 days from transplant)',
    soilAndWater: 'Loose, friable loamy soil amended with rich organic compost (pH 6.0–6.8). Requires steady, even soil moisture to avoid bitter, tough leaves.',
    sunlight: 'Full sunlight to partial shade (4–6 hours daily; partial afternoon shade buffers hot dry months)',
    growingTips: [
      'Stagger planting with bi-weekly sowings to avoid simultaneous harvesting and ensure fresh leaves on demand.',
      'Harvest whole plants at 30 days while leaves are tender, or cut outer leaves as needed for immediate kitchen use.',
      'Repel aphids and diamondback moths organically by dusting plants with wood ash or spraying neem seed extract.',
      'Blend compost and carbonized rice hull into raised seedbeds to maintain soil moisture without causing damping-off.',
    ],
  },
  {
    id: 'saluyot',
    name: "Jute Mallow / Jew's Mallow",
    localName: 'Saluyot',
    scientificName: 'Corchorus olitorius',
    category: 'leafy_greens',
    image: IMAGES.saluyot,
    summary: 'A staple vegetable deeply anchored in Northern Luzon and Ilocano cuisine, providing the classic silky, mucilaginous body to Dinengdeng, Inabraw, and Pinakbet. Rich in beta-carotene, iron, calcium, vitamin E, and soluble fiber.',
    plantingSeason: 'Year-round; peaks in productivity during the warm rainy months (April to November)',
    daysToHarvest: '30–45 days from seeding (continuous harvesting for 3–4 months)',
    soilAndWater: 'Tolerant of diverse soil types from sandy loam to heavy clay; prefers organic-rich, moist soil. Withstands temporary wet spells and heavy rains.',
    sunlight: 'Full tropical sun (6–8 hours daily); thrives under hot temperatures and high humidity',
    growingTips: [
      'Scarify seeds by soaking in warm water for 12–24 hours prior to sowing to break dormancy and ensure high germination.',
      'Pinch or snip the top 10–15 cm of tender growing tips every 10–14 days to harvest and stimulate dense lateral branching.',
      'Mulch heavily with rice straw to suppress weeds and maintain consistent root zone moisture throughout hot dry spells.',
      'Allow select healthy stalks to produce brown seed capsules at the end of the season; collect and save dry seeds for replanting.',
    ],
  },
  {
    id: 'kulitis',
    name: 'Native Amaranth / Slender Amaranth',
    localName: 'Kulitis',
    scientificName: 'Amaranthus viridis',
    category: 'leafy_greens',
    image: IMAGES.kulitis,
    summary: 'A versatile indigenous leafy vegetable central to regional Filipino peasant dishes such as Visayan Laswa, Ilocano Dinengdeng, and sautéed Ginisang Gulay. It is a nutritional powerhouse loaded with iron, calcium, magnesium, and vitamin C.',
    plantingSeason: 'Year-round; grows most vigorously during warm, humid months (March to October)',
    daysToHarvest: '25–35 days from seeding (baby greens ready at 15–20 days)',
    soilAndWater: 'Extremely resilient to poor, marginal, or sandy soils; produces best in well-drained loam with compost. Drought-hardy once established.',
    sunlight: 'Full direct sunlight (6+ hours daily); utilizes C4 photosynthesis to thrive in intense tropical heat',
    growingTips: [
      'Mix the microscopic seeds with dry river sand or fine compost before broadcasting to achieve even spacing across beds.',
      'Thin seedlings at two weeks and utilize the tender thinnings as nutritious gourmet baby microgreens in dishes.',
      'Harvest by cutting tender shoot tops 5–10 cm above ground level, allowing axillary buds to ratoon for repeated harvests.',
      'Let 1–2 mature plants go to seed in the garden plot to naturally re-seed the area for an effortless, perpetual annual crop.',
    ],
  },

  // ==========================================
  // ROOT CROPS & TUBERS (Lamang-Lupa)
  // ==========================================
  {
    id: 'kamote',
    name: 'Sweet Potato',
    localName: 'Kamote',
    scientificName: 'Ipomoea batatas',
    category: 'root_crops',
    image: IMAGES.kamote,
    summary: 'A resilient, nutrient-dense secondary carbohydrate staple that provides crucial food security across the Philippine archipelago. Both the vitamin-rich underground storage roots and tender shoot tips (talbos ng kamote) are heavily utilized in everyday home cooking.',
    plantingSeason: 'Year-round; best planted in May to July (wet season) or October to November (dry season)',
    daysToHarvest: '90–120 days from planting vine cuttings',
    soilAndWater: 'Well-drained, loose sandy loam or volcanic loam with pH 5.5–6.5. Moderate water needs; sensitive to waterlogging which induces root rot.',
    sunlight: 'Full sun (at least 6 hours of unshaded sunlight daily)',
    growingTips: [
      'Plant healthy apical vine tip cuttings (25–35 cm long) into raised ridges or mounds at a 45-degree angle, leaving 3–4 nodes buried.',
      'Construct raised ridges 30–40 cm high to optimize drainage, accommodate unrestricted lateral tuber swelling, and make manual harvest effortless.',
      'Perform vine turning or lifting at 45–60 days after planting to prevent adventitious rooting along trailing nodes.',
      'Cure freshly harvested tubers under shade in a warm, well-ventilated spot for 5–7 days to convert starches to sugars for improved sweetness.',
    ],
  },
  {
    id: 'kamoteng_kahoy',
    name: 'Cassava',
    localName: 'Kamoteng Kahoy',
    scientificName: 'Manihot esculenta',
    category: 'root_crops',
    image: IMAGES.kamoteng_kahoy,
    summary: 'A drought-tolerant tropical root crop that serves as a vital staple food reserve in Mindanao and the Visayas, an industrial raw material for starch manufacturing, and the primary base for beloved native delicacies like cassava cake and pitsi-pitsi.',
    plantingSeason: 'April to June (onset of rainy season) or October to November in regions with year-round rainfall',
    daysToHarvest: '8–10 months for culinary table varieties; 10–12 months for industrial high-starch cultivars',
    soilAndWater: 'Loose, well-aerated sandy loam or light clay loam rich in organic matter (pH 5.0–6.5). Highly drought-tolerant once established.',
    sunlight: 'Full sun (requires 7–8 hours of intense daily sunshine for maximum root bulking)',
    growingTips: [
      'Select mature, pest-free stem stakes (20–25 cm long with 5–7 viable nodes) from the middle portion of healthy plants, planting them vertically or slightly angled.',
      'Hill up loose soil around plant bases at 2–3 months after planting to promote extensive tuber bulking and anchor root systems against typhoons.',
      'Process or cook harvested roots within 48–72 hours of extraction, as cassava tubers suffer rapid post-harvest physiological vascular streaking.',
      'Boil culinary varieties thoroughly or properly peel, grate, squeeze, and ferment bitter industrial varieties to eliminate cyanogenic glucosides.',
    ],
  },
  {
    id: 'gabi',
    name: 'Taro',
    localName: 'Gabi',
    scientificName: 'Colocasia esculenta',
    category: 'root_crops',
    image: IMAGES.gabi,
    summary: 'An esteemed wetland and upland root crop celebrated throughout Philippine gastronomy, prized for its starchy corms, succulent stems, and tender leaves. It is the defining ingredient of the famous Bicolano coconut-braised dish Laing, while its corms provide thickness to sinigang broths.',
    plantingSeason: 'Year-round in wetlands with continuous water; May to June or October to November for rainfed upland plots',
    daysToHarvest: '6–8 months for lowland flooded varieties; 8–10 months for upland dryland corms',
    soilAndWater: 'Fertile, organic-rich muck soils or heavy clay loam with high water-holding capacity (pH 5.5–7.0). Thrives in saturated, flooded, or moist marshy conditions.',
    sunlight: 'Full sun to partial shade (tolerates 20–30% filtered shade, making it ideal for coconut intercropping)',
    growingTips: [
      'Propagate using corm-tops (huli) consisting of the top 1–2 cm of the corm with 15–20 cm of petiole base intact for rapid, vigorous root establishment.',
      'Continuously hill up fertile soil and compost around expanding corms every 2 months to shield tubers from direct sunlight and prevent bitter green skins.',
      'Maintain saturated soil or shallow standing water throughout the vegetative stage, withholding irrigation 2–3 weeks before harvest.',
      'Never consume raw tissues; always boil or stew thoroughly with acid (vinegar or tamarind) to neutralize irritating calcium oxalate raphide needles.',
    ],
  },
  {
    id: 'ube',
    name: 'Purple Yam',
    localName: 'Ube',
    scientificName: 'Dioscorea alata',
    category: 'root_crops',
    image: IMAGES.ube,
    summary: 'The iconic, world-famous purple tuber that represents the crown jewel of Philippine dessert culture and celebratory heritage food. Valued for its vivid violet color and naturally sweet, nutty flavor, it is the indispensable foundation of authentic ube halaya, halo-halo, and pastillas.',
    plantingSeason: 'March to May (planted during late dry season so setts break dormancy with monsoonal rains)',
    daysToHarvest: '8–9 months (typically harvested from December to February when foliage withers)',
    soilAndWater: 'Deep, loose, fertile sandy loam or volcanic loam with excellent internal drainage and rich humus (pH 5.5–6.5). Requires generous, well-distributed rain during vine climbing.',
    sunlight: 'Full sun to partial light (vines must receive open direct sunlight on trellises for optimal photosynthesis)',
    growingTips: [
      'Prepare 100–150g setts cut from healthy, dormant mother tubers (head and tail cuts sprout fastest), dusting cut surfaces with wood ash before planting.',
      'Install sturdy 2-meter bamboo stakes or overhead trellis grids (balag) early as shoots emerge to elevate vines and curb anthracnose foliar disease.',
      'Harvest carefully when the leaves yellow, wither, and completely dry up, digging gently with wooden spatulas to avoid scratching the tender skin.',
      'Cure freshly dug tubers in a dry, shaded, and well-ventilated storeroom for 1–2 weeks to toughen the skin and extend storage life.',
    ],
  },

  // ==========================================
  // GRAINS & CEREALS (Butil)
  // ==========================================
  {
    id: 'palay',
    name: 'Paddy Rice',
    localName: 'Palay',
    scientificName: 'Oryza sativa',
    category: 'grains',
    image: IMAGES.palay,
    summary: 'The primary staple grain and cultural backbone of the Philippines, providing daily nourishment to over 100 million Filipinos and underpinning rural agricultural livelihoods. Cultivated extensively in lowland irrigated paddies and rainfed river basins across Central Luzon, Cagayan Valley, and Western Visayas.',
    plantingSeason: 'Wet season: June to August; Dry season: November to January (with irrigation)',
    daysToHarvest: '105–120 days (early varieties) or 120–135 days (medium-maturing varieties) from seeding',
    soilAndWater: 'Heavy clay or clay loam with an impermeable hardpan subsoil (pH 5.5–6.5) to retain water. Requires saturated conditions to 3–5 cm depth; drain fields 7–10 days before harvest.',
    sunlight: 'Full direct sunlight (at least 6–8 hours daily, especially critical during panicle development and grain filling)',
    growingTips: [
      'Adopt Alternate Wetting and Drying (AWD) using an observation tube (obser-tubo) to conserve up to 30% irrigation water without yield penalty.',
      'Transplant young 18–21 day-old seedlings at 1–2 seedlings per hill with 20 cm x 20 cm spacing to encourage vigorous tillering.',
      'Use the Leaf Color Chart (LCC) to calibrate nitrogen top-dressing at early tillering and panicle initiation, avoiding excessive vegetative lodging.',
      'Drain paddy water 7–10 days before the projected harvest date to ensure uniform grain ripening and harden the soil.',
    ],
  },
  {
    id: 'mais',
    name: 'Corn / Maize',
    localName: 'Mais',
    scientificName: 'Zea mays',
    category: 'grains',
    image: IMAGES.mais,
    summary: 'The second most vital cereal crop in the Philippines, consumed as white corn grits in the Visayas and Mindanao and utilized as yellow corn for livestock feed nationwide. Boiled sweet corn cobs and grilled native lagkitan ears are cherished merienda street snacks along Philippine roadsides.',
    plantingSeason: 'Wet season: May to June (onset of monsoons); Dry season: October to December (following rice harvest)',
    daysToHarvest: '65–75 days for fresh green sweet corn; 100–115 days for mature dry field grain corn',
    soilAndWater: 'Deep, well-drained, friable silt loam or sandy loam rich in organic matter (pH 5.8–6.8). Requires consistent soil moisture during flowering and silking.',
    sunlight: 'Full direct sunlight (minimum 6–8 hours daily, unshaded)',
    growingTips: [
      'Perform hilling-up (pahabol / paso) at 21–28 days after planting to suppress emerging weeds, anchor brace roots, and prevent lodging from heavy winds.',
      'Scout weekly for Fall Armyworm (FAW / Harabas) during the whorl stage; release Trichogramma chilonis wasps or apply Bacillus thuringiensis (Bt) sprays.',
      'Ensure uninterrupted soil moisture during the critical tasseling and silking windows, as moisture deficit at pollination causes barren cobs.',
      'Harvest green table corn early in the morning when tassels dry brown and kernels exude milk when pierced; dry grain corn to 14% moisture before bagging.',
    ],
  },

  // ==========================================
  // SPICES & AROMATICS (Pampalasa)
  // ==========================================
  {
    id: 'siling_labuyo',
    name: "Bird's Eye Chili",
    localName: 'Siling Labuyo',
    scientificName: 'Capsicum frutescens',
    category: 'spices',
    image: IMAGES.siling_labuyo,
    summary: 'The fiery native Philippine wild chili pepper. Tiny, conical fruits point straight upwards with Scoville heat ratings of 80,000–100,000 SHU.',
    plantingSeason: 'Year-round in warm lowlands; best started in October–December',
    daysToHarvest: '75–90 days from transplanting',
    soilAndWater: 'Well-draining soil mixed with sand and compost. Moderately drought-tolerant; avoid soggy roots.',
    sunlight: 'Full sun; thrives in warm tropical temperatures (24°C–32°C)',
    growingTips: [
      'Pinch growing tips when seedlings reach 15 cm tall to encourage bushy, branchy growth.',
      'Apply wood ash or potassium-rich compost to stimulate abundant flowering and heat.',
      'Wear gloves when picking to avoid skin irritation from concentrated capsaicin.',
    ],
  },
  {
    id: 'siling_haba',
    name: 'Green Finger Chili / Espada',
    localName: 'Siling Haba',
    scientificName: 'Capsicum annuum var. longum',
    category: 'spices',
    image: IMAGES.siling_haba,
    summary: 'Long, smooth, light-green finger chili indispensable in Philippine culinary broth dishes like Sinigang, Paksiw, and Bicol Express. Imparts fragrant mild heat.',
    plantingSeason: 'October to February (dry season) or June to July (wet season)',
    daysToHarvest: '65–75 days after transplanting',
    soilAndWater: 'Well-drained sandy loam or clay loam rich in organic matter. Regular, moderate moisture.',
    sunlight: 'Full sun (6+ hours daily)',
    growingTips: [
      'Stake tall plants with bamboo sticks to prevent branches breaking under heavy crop load.',
      'Harvest while glossy green and firm before they turn mature orange-red.',
      'Mulch with rice straw to conserve soil moisture and prevent fungal soil splash.',
    ],
  },
  {
    id: 'bawang',
    name: 'Garlic',
    localName: 'Bawang',
    scientificName: 'Allium sativum',
    category: 'spices',
    image: IMAGES.bawang,
    summary: 'The indispensable aromatic cornerstone of Philippine culinary identity, establishing the ubiquitous gisa (sautéed base) alongside onions and tomatoes in virtually every Filipino savory recipe. Native varieties like Ilocos White (Ilocos Gold) and Batanes Red are celebrated for their intense aroma and pungency.',
    plantingSeason: 'October to December (dry season planting capitalizing on cool nights and dry sunny harvest weather)',
    daysToHarvest: '90–105 days for native Ilocos varieties; 110–120 days for larger bulb cultivars',
    soilAndWater: 'Well-drained, loose, fertile sandy loam or silt loam high in organic matter (pH 6.0–6.8). Stop all watering 2–3 weeks before harvest to prevent bulb rot.',
    sunlight: 'Full direct sunlight (at least 8 hours of unobstructed sun daily)',
    growingTips: [
      'Separate large, healthy outer cloves immediately prior to planting and set them upright in mulched beds with tips flush at the soil surface at 10 cm x 10 cm spacing.',
      'Apply a thick 5–8 cm blanket of dry rice straw mulch over planting beds right after planting to suppress weed growth and conserve moisture.',
      'Cease irrigation completely once 70–75% of the upper foliage yellows and lodges naturally, allowing bulbs to firm up in dry earth.',
      'Harvest during clear weather by pulling entire plants, braiding foliage into traditional hanging clusters (mandala), and curing in a breezy shed for 2–4 weeks.',
    ],
  },
  {
    id: 'sibuyas',
    name: 'Red Onion',
    localName: 'Sibuyas',
    scientificName: 'Allium cepa',
    category: 'spices',
    image: IMAGES.sibuyas,
    summary: 'A major commercial cash crop and an essential kitchen daily in the Philippines, providing aromatic depth and sweetness to sautéed bases, broths, and sawsawan dips. Production is heavily concentrated in Nueva Ecija (the Onion Capital of the Philippines), Pangasinan, and Mindoro.',
    plantingSeason: 'October to December (nursery seedbed); transplanting into open fields from November to January',
    daysToHarvest: '85–100 days from transplanting (or 110–130 days from direct seeding)',
    soilAndWater: 'Deep, friable, fertile sandy loam or silt loam with good drainage and neutral pH (6.0–7.0). Requires steady moisture during bulb enlargement; highly sensitive to standing water.',
    sunlight: 'Full direct sun (requires 6–8+ hours of intense, unshaded sunlight daily)',
    growingTips: [
      'Transplant sturdy, pencil-thick seedlings (40–45 days old) into well-pulverized raised beds in the late afternoon to minimize transplant shock.',
      'Maintain shallow furrow irrigation during active vegetative leafing and bulb expansion, withholding all water 10–14 days prior to harvest.',
      'Harvest when 50–70% of the field foliage weakens at the neck and topples over naturally (neck fall), confirming full bulb maturity.',
      'Field-cure pulled bulbs under light straw shade for 3–5 days, clip foliage to a 2 cm neck, and dry thoroughly on slatted wooden racks.',
    ],
  },
  {
    id: 'luya',
    name: 'Ginger',
    localName: 'Luya',
    scientificName: 'Zingiber officinale',
    category: 'spices',
    image: IMAGES.luya,
    summary: 'A vital culinary rhizome and honored traditional herbal remedy across the Philippines, imparting lively heat and eliminating gamey or fishy aromas in tinola, paksiw, kinilaw, and arroz caldo. It is the primary ingredient of salabat, the beloved ginger decoction for colds and throat soothing.',
    plantingSeason: 'April to May (onset of southwest monsoons) or year-round with supplemental irrigation',
    daysToHarvest: '5–6 months for tender young ginger rhizomes; 8–10 months for fully mature, pungent, fibrous ginger',
    soilAndWater: 'Light, porous, well-aerated sandy loam or volcanic loam with high organic humus (pH 5.5–6.5). Requires generous moisture, but waterlogging causes fatal bacterial wilt.',
    sunlight: 'Partial shade (30–50% filtered sunlight) or open sun with intercropped coconut, banana, or agroforestry canopy cover',
    growingTips: [
      'Plant pre-sprouted seed rhizome pieces (30–50g with 2–3 active eye buds) into deep, well-drained raised beds treated with organic compost.',
      'Mulch heavily with dry rice straw or dried banana leaves to insulate roots against intense heat, prevent weed emergence, and maintain steady moisture.',
      'Hill up loose, organic-rich soil over emerging rhizomes 2–3 times during the growing cycle to prevent exposed greening and promote lateral branching.',
      'Harvest by carefully loosening soil with a garden fork during dry weather to prevent skin puncture, brush away excess soil, and cure under shade.',
    ],
  },
  {
    id: 'tanglad',
    name: 'Lemongrass',
    localName: 'Tanglad',
    scientificName: 'Cymbopogon citratus',
    category: 'spices',
    image: IMAGES.tanglad,
    summary: 'A fragrant perennial grass packed with citrusy essential oils, renowned as an essential seasoning in Philippine regional cooking, most famously knotted and stuffed into Cebu lechon and chicken inasal. Beyond the kitchen, it is widely brewed as a detoxifying herbal tea.',
    plantingSeason: 'Year-round in tropical conditions; optimal planting at the onset of rains from May to July',
    daysToHarvest: '90–120 days from planting vegetative slips for first harvest; periodic selective cutting every 60–90 days thereafter',
    soilAndWater: 'Adaptable to a broad range of soils from sandy loam to clay loam (pH 5.5–7.5), provided drainage is adequate. Highly drought-resilient once rooted.',
    sunlight: 'Full direct sun (demands 6–8 hours of intense tropical sunshine daily)',
    growingTips: [
      'Propagate using mature outer slips or tillers trimmed to 15–20 cm in length, soaking the basal root plates in water for 24–48 hours until root swellings emerge.',
      'Plant slips at a 45-degree angle with 2–3 slips per hill spaced 60–90 cm apart, firming moist soil around the base to accelerate clump formation.',
      'Trim brown outer leaves and cut back tall top foliage periodically to rejuvenate clump vigor and stimulate new tillers.',
      'Harvest individual mature pseudostems by selecting outer stalks at least 1.5 cm thick, slicing cleanly at ground level while leaving the inner tillers to regrow.',
    ],
  },
];

/** 4 mixed crops representing Fruits, Vegetables, and Spices for the 2x2 preview card */
export const PREVIEW_CROPS: AlmanacCrop[] = [
  ALMANAC_CROPS.find(c => c.id === 'mangga')!,
  ALMANAC_CROPS.find(c => c.id === 'ampalaya')!,
  ALMANAC_CROPS.find(c => c.id === 'kalabasa')!,
  ALMANAC_CROPS.find(c => c.id === 'siling_labuyo')!,
];
